name: Android Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build Debug APK
      run: ./gradlew assembleDebug
      
    # List the generated APK file to verify it exists
    - name: List APK files
      run: |
        echo "Generated APK files:"
        find app/build/outputs/apk -name "*.apk"
        
    # Create a temporary directory for artifacts
    - name: Create artifacts directory
      run: |
        mkdir -p /tmp/artifacts
        cp app/build/outputs/apk/debug/app-debug.apk /tmp/artifacts/
        
    # Try alternate upload method if the standard one fails
    - name: Upload Debug APK (alternative method)
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: /tmp/artifacts/app-debug.apk
        retention-days: 3
        if-no-files-found: error
