name: Android Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Find Android project
        id: find-project
        run: |
          if [ -f "build.gradle" ] && [ -d "app" ] && [ -f "app/build.gradle" ]; then
            echo "PROJECT_DIR=." >> $GITHUB_ENV
            echo "Project found in root directory"
          elif [ -f "aptlinks/build.gradle" ] && [ -d "aptlinks/app" ] && [ -f "aptlinks/app/build.gradle" ]; then
            echo "PROJECT_DIR=aptlinks" >> $GITHUB_ENV
            echo "Project found in aptlinks directory"
          else
            echo "PROJECT_DIR=aptlinks" >> $GITHUB_ENV
            echo "Defaulting to aptlinks directory"
          fi

      - name: Setup Gradle wrapper
        run: |
          cd $PROJECT_DIR
          mkdir -p gradle/wrapper
          
          # Create wrapper properties
          echo "distributionBase=GRADLE_USER_HOME" > gradle/wrapper/gradle-wrapper.properties
          echo "distributionPath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          echo "distributionUrl=https\\://services.gradle.org/distributions/gradle-8.1.1-all.zip" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStoreBase=GRADLE_USER_HOME" >> gradle/wrapper/gradle-wrapper.properties
          echo "zipStorePath=wrapper/dists" >> gradle/wrapper/gradle-wrapper.properties
          
          # Download wrapper jar
          curl -L -o gradle/wrapper/gradle-wrapper.jar https://github.com/gradle/gradle/raw/master/gradle/wrapper/gradle-wrapper.jar
          
          # Create gradlew script
          echo '#!/bin/sh' > gradlew
          echo 'exec java -classpath gradle/wrapper/gradle-wrapper.jar org.gradle.wrapper.GradleWrapperMain "$@"' >> gradlew
          chmod +x gradlew
          
          # Create gradlew.bat
          echo '@echo off' > gradlew.bat
          echo 'java -classpath "%~dp0\gradle\wrapper\gradle-wrapper.jar" org.gradle.wrapper.GradleWrapperMain %*' >> gradlew.bat

      - name: Build with Gradle
        run: |
          cd $PROJECT_DIR
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: "${{ env.PROJECT_DIR }}/app/build/outputs/apk/debug/*.apk"
          if-no-files-found: warn
